tags:
- name: ads
  description: ads API

paths:
# [GET] ads
  /apiv1/ads:
    get:
      tags:
      - ads
      summary: Find All ads
      parameters:
      - name: name
        in: query
        description: ad name
        required: false
        type: string
        example: 'bicicleta'
      - name: sale
        in: query
        description: ad sale
        required: false
        type: boolean
        example: 'true'
      - name: price
        in: query
        description: ad price
        required: false
        type: float
        example: '230.15'
      - name: tags
        in: query
        description: ad tags
        required: false
        type: array
        example: ['lifestyle', 'motor']
      - name: minprice
        in: query
        description: ad minprice
        required: false
        type: float
        example: '230.00'
      - name: maxprice
        in: query
        description: ad maxprice
        required: false
        type: float
        example: '500.00'
      - name: skip
        in: query
        description: ad skip
        required: false
        type: integer
        example: '1'
      - name: limit
        in: query
        description: ad limit
        required: false
        type: integer
        example: '3'
      - name: select
        in: query
        description: ad select field
        required: false
        type: field
        example: 'name'
      - name: sort
        in: query
        description: ad sort field
        required: false
        type: field
        example: 'name'
      responses:
        200:
          description: 'OK'
        422:
          description: 'Unprocessable Entity'
        500:
          description: 'Server Error'


# [POST] ads
    post:
      tags:
      - ads
      summary: Add Ad
      parameters:
      - name: body
        in: body
        description: ad Data
        required: false
        schema:
          type: object
          properties:
            name: 
              type: string
              descirption: ad name
              example: 'bicicleta'
            sale: 
              type: boolean
              descirption: ad sale
              example: 'true'
            price: 
              type: float
              descirption: ad price
              example: '20.00'
            photo: 
              type: string
              descirption: ad photo
              example: 'bicicleta.jpeg'
            tags: 
              type: array
              descirption: ad tags
              example: ['lifestyle', 'motor']
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        422:
          description: 'Unprocessable Entity'
        500:
          description: 'Server Error'

# [GET] ads/tagslist
  /apiv1/ads/tagslist:
    get:
      tags:
      - ads
      summary: Find All tags
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
          
# definitions
definitions:
  Ads:
    type: object
    required:
    properties:
      name:
        type: string
        description: ad name
      sale:
        type: boolean
        description: ad sales
      price:
        type: float
        description: ad price
      photo:
        type: string
        description: ad photo
      tags:
        type: array<string>
        description: ad tags

schemes:
 - http
